stages:
  - validate

tffmt:
  stage: validate
  image: hashicorp/terraform:0.11.10
  tags:
    - default
  script:
    - terraform fmt -write=false -diff -check

tfvalidate:
  stage: validate
  image: hashicorp/terraform:0.11.10
  tags:
    - default
  script:
    - mv terraform.tfvars.ci terraform.tfvars
    - terraform init
    - terraform validate
